開発用ブランチ（できた機能はここにマージ）
shirasu-aq/carousel_React_practice pull request #4
Opened 2021-06-14 14:19 UTC by shirasu-aq

2021-06-16 06:34 UTC, shirasu-aq commented on src/data.js
> +    img: `${process.env.PUBLIC_URL}/fruits/category_tn_190.jpeg`,
ちなみに先ほど質問していたことですが、
①画像ディレクトリをpublicに移動させる。
②```process.env.PUBLIC_URL```を通じてpublic内のパスをimgに通す。
といった方法で解決しました。

ちなみにこれは、相対パスはhtmlファイルが置かれている場所を基準にするので、srcではなくpublicに画像を置くべきなのだなとわかりました。

2021-06-16 06:44 UTC, shirasu-aq commented on src/Fruits.js
> +    }
**[Q]**
JavaScriptの時と使用する演算子が異なったのが気になりました。
訂正前の赤部分はJavaScriptでカルーセルを作った時のコードで、修正後の緑部分は成功したコードです。

```＞```の時に成功せず、```===```で成功したのはReact特有のレンダリングのタイミングと関係あるのかな？と思いました。

ちなみにJavaScriptで実験したところ、```===```だと、表示できるデータが配列の要素1つ分減ってしまいました。

こちらあまり深いことは考えずに、「こういうものなんだ」で進めてしまって大丈夫でしょうか。
補足などあったら聞きたいです。

2021-06-16 06:46 UTC, shirasu-aq commented
**[Q]**
ファイル構成なのですが、今回は
```
①App.js :タイトル部分
②Fruits.js :データ表示部分、ボタン部分
③data.js :情報を格納しただけ
```
というように作成しました。

Reactだと細かくファイルを分けているイメージなのですが、今回の構成はこれで良いでしょうか？

2021-06-16 07:15 UTC, tatsuya-asami commented on src/data.js
> +    img: `${process.env.PUBLIC_URL}/fruits/category_tn_190.jpeg`,
create-react-appで作ったアプリケーションに関してはこの書き方であっていると思います。ただこれはcreate-react-appに限った話なので補足します。

`process.env.PUBLIC_URL`は環境変数で、create-react-appが指定しているもの以外は自分で設定する必要があります。
srcでなくpublicに画像を置く必要があるかどうかはcreate-react-appが決めていることです。

わかっておくべき部分はこれらです。

1. 絶対パスと相対パスの違い。
2. 環境変数とはなにか。また、`process.env`とはどういう意味を持っているのか。

2021-06-16 07:19 UTC, tatsuya-asami commented on src/Fruits.js
> +    }
レンダリングのタイミングと関係ありますね。直前でcountを1つ増やしているため、存在しないimgを読み込みに言っているのかと思います。

同じ関数の中でsetCountを2回実行するとこのようなことが発生するので、この書き方は避けたほうが良いです。

2021-06-16 07:20 UTC, tatsuya-asami commented
> **[Q]**
> ファイル構成なのですが、今回は
> 
> ```
> ①App.js :タイトル部分
> ②Fruits.js :データ表示部分、ボタン部分
> ③data.js :情報を格納しただけ
> ```
> 
> というように作成しました。
> 
> Reactだと細かくファイルを分けているイメージなのですが、今回の構成はこれで良いでしょうか？

良いと思います。細かい話は難しいので、自分が良いと思った分け方で書いてもらえればとりあえず大丈夫です。

2021-06-16 07:31 UTC, tatsuya-asami requested changes

2021-06-16 07:31 UTC, tatsuya-asami commented on src/Fruits.js
> +  };
- MUST
setCountを同じ関数で2回実行するのは良くないです。意図してないレンダリングが発生してしまうためですね。先に条件分岐して、setCountは一度だけ発火するようにしましょう。

厳密な話をするとcount + 1という書き方も好ましくないのですが、気にしなくて良いです。

```js
  const increase = () => {
    if (count >= fruitsData.length - 1) {
      setCount(0);
    } else {
      setCount(count + 1);
    }
  };

```

2021-06-16 07:31 UTC, tatsuya-asami commented on src/Fruits.js
> +    <>
- nits
不要なタグなので消しましょう。

2021-06-16 07:31 UTC, tatsuya-asami commented on src/Fruits.js
> +          <img src={fruitsData[count].img} id="img" alt=""></img>
- IMO
altは画像が表示されない時に表示するものなので、空文字にせずに説明を入れましょう。今回はりんごとかバナナになると思います。

詳しくは調べてみて下さい。

2021-06-16 07:31 UTC, tatsuya-asami commented on src/Fruits.js
> +          <h4 id="fruits">{fruitsData[count].fruitsName}</h4>
- IMO
不要なidと思われる物が残っています。
reactではidから要素を取得することはほぼないので、基本的にidは付与しないです。
cssのセレクターにはidではなくclassNameを指定するようにしましょう。

2021-06-16 07:31 UTC, tatsuya-asami commented on src/Fruits.scss
> +}
IMO
せっかくscssを使っているので、scssの書き方を使いましょう。

2021-06-16 08:26 UTC, shirasu-aq commented on src/Fruits.js
> +    }
承知しました。
修正については下で同様の指摘があるので、そこで直します。

2021-06-16 08:56 UTC, shirasu-aq commented on src/Fruits.js
> +      setCount(count + 1);
テスト

2021-06-16 09:33 UTC, shirasu-aq commented on src/Fruits.js
> +  };
929f3c7 修正しました。

>setCountを同じ関数で2回実行するのは良くないです。意図してないレンダリングが発生してしまうためですね。先に条件分岐して、setCountは一度だけ発火するようにしましょう。

承知しました。

**[Q]**
> count + 1という書き方も好ましくない

こちらもう少し聞いても良いですか！

2021-06-16 09:34 UTC, shirasu-aq commented on src/Fruits.js
> +    <>
7ba6441 修正しました。

2021-06-16 09:36 UTC, shirasu-aq commented on src/Fruits.js
> +          <img src={fruitsData[count].img} id="img" alt=""></img>
1ba3bc9 修正しました。
動作確認し、画像がない時に表示できるか確かめました。

2021-06-16 09:37 UTC, shirasu-aq commented on src/Fruits.js
> +          <h4 id="fruits">{fruitsData[count].fruitsName}</h4>
def91c6 修正しました。

> cssのセレクターにはidではなくclassNameを指定するようにしましょう。

承知しました。

2021-06-16 09:37 UTC, shirasu-aq commented on src/Fruits.scss
> +}
c2c7532 修正しました。

2021-06-16 10:34 UTC, shirasu-aq commented on src/data.js
> +    img: `${process.env.PUBLIC_URL}/fruits/category_tn_190.jpeg`,
**[Q]**
> 2. 環境変数とはなにか。また、`process.env`とはどういう意味を持っているのか。

環境変数：OSが参照する設定を保存するためのもの。
PATHとかがその例。

process.env：Node.jsの環境変数が```process.env```というオブジェクトに収納されている。
(Node.jsが認識する全ての環境変数を出力できる。）
特定の環境変数を取得するにはprocess.env.XXとする。（例えば今回もちいた```PUBLIC_URL```はcreate-react-appが指定。）
代入や変更も可能

こちらで理解あっているでしょうか？
（正直、何も知らない人にうまく説明しろと言われるとあまり自信がないです。）

2021-06-17 02:03 UTC, tatsuya-asami commented on src/data.js
> +    img: `${process.env.PUBLIC_URL}/fruits/category_tn_190.jpeg`,
あってます！

フロントエンドではほぼほぼ`process.env`を使った環境変数しか関係があることはないです。
開発環境と本番環境で変数を変えたい時に主に使います。（まさに環境変数ですね）

具体的にはAPI等のURLを環境変数で切り替えるために、ほぼすべてのプロジェクトで使います。

2021-06-17 02:06 UTC, tatsuya-asami commented on src/Fruits.js
> +  };
ほぼほぼ問題になることはないのでやめておきましょう。
一応こちらに書いてあります。

https://ja.reactjs.org/docs/hooks-reference.html#basic-hooks

2021-06-17 02:15 UTC, tatsuya-asami commented on src/data.js
> +    alt: "Peach!",
- nits
基本的に表示されるものではなく、「画像の説明」なので、`!`は不要です。

2021-06-17 02:46 UTC, shirasu-aq commented on src/Fruits.js
> +  };
承知しました。
（確認しておきます。）

2021-06-17 02:51 UTC, shirasu-aq commented on src/data.js
> +    alt: "Peach!",
5172586 こちら修正しました。

2021-06-17 03:26 UTC, tatsuya-asami approved these changes
1. 色々作成してdevelopにマージする
2. developでレビュー依頼する。
3. その修正を別のブランチで行ってdevelopにマージする。

みたいなのはgithubの運用として紛らわしいのでやめましょう。
1つのブランチで1つのプルリク、修正もそのブランチ上で行いたいです。

引き続き自分で色々ブランチを切ってdevelopにマージしてからレビュー依頼をしたいのであれば、指摘後の修正はdevelopで行うようにしましょう。

![image](https://user-images.githubusercontent.com/46734354/122325482-a57cd400-cf65-11eb-9e97-d56d248c0bd5.png)

2021-06-17 04:05 UTC, shirasu-aq commented
> 1. 色々作成してdevelopにマージする
> 2. developでレビュー依頼する。
> 3. その修正を別のブランチで行ってdevelopにマージする。
> 
> みたいなのはgithubの運用として紛らわしいのでやめましょう。
> 1つのブランチで1つのプルリク、修正もそのブランチ上で行いたいです。
> 
> 引き続き自分で色々ブランチを切ってdevelopにマージしてからレビュー依頼をしたいのであれば、指摘後の修正はdevelopで行うようにしましょう。
> 
> ![image](https://user-images.githubusercontent.com/46734354/122325482-a57cd400-cf65-11eb-9e97-d56d248c0bd5.png)

承知しました。
機能ごとにブランチきって作って、完成させたらdevelopにマージしてレビューもらう形でいきたいので、今後の実装では、レビューで指摘されたものに関してはdevelopで修正行うようにします。

2021-06-17 05:56 UTC, merged

2021-06-17 09:15 UTC, shirasu-aq commented on src/Fruits.scss
> +    }
imgテストコメント